[package]
name = "sweetmcp-voice-tools"
version = "0.1.0"
edition = "2024"
authors = ["David Maple<david@cyrup.ai>"]
description = "MCP voice tool definitions for text-to-speech and speech-to-text operations"
license = "MIT OR Apache-2.0"
repository = "https://github.com/cyrusnimda/paraphym"
keywords = ["mcp", "voice", "tts", "stt", "audio"]
categories = ["multimedia::audio", "api-bindings"]

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
anyhow = "1.0.100"
thiserror = "2.0.17"

# For async trait definitions
async-trait = "0.1.89"
tokio = { version = "1.47", features = ["sync"] }
