[workspace]
resolver = "3"
members = [
    "packages/simd",
    "packages/candle",
]
exclude = ["tmp/candle", "tmp/*", "forks/surrealdb"]


[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["CYRUP AI"]
repository = "https://github.com/cyrup-ai/paraphym"

