[package]
name = "cylo"
version = "0.1.0"
edition = "2024"
description = "Secure multi-language code execution service"
authors = ["CYRUP AI"]
repository = "https://github.com/cyrup-ai/fluent-ai"
license = "MIT"

[dependencies]
# Core dependencies with latest versions

anyhow = "1.0.100"
serde = { version = "1.0.228", features = ["derive"] }
tracing = "0.1.41"
thiserror = "2.0.17"
clap = { version = "4.5", features = ["derive", "cargo"] }
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
tempfile = "3.23.0"
chrono = { version = "0.4.42", features = ["serde"] }
uuid = { version = "1.18.1", features = ["v4", "serde"] }
tokio = { version = "1.47.1", features = ["full"] }
termcolor = "1.4.1"
# fluent_ai_domain = { path = "../domain" } # Removed to avoid circular dependency
cyrup_sugars = { git = "https://github.com/cyrup-ai/cyrup-sugars", branch = "main", package = "cyrup_sugars", features = ["all"] }

# Regular dependencies
nix = { version = "0.30.1", features = ["user", "sched"] }
libc = "1.0.0-alpha.1"
num_cpus = "1.17.0"

# Additional dependencies
statig = "0.4.1"
watchexec = "8.0.1"
watchexec-events = "6.0.0"
watchexec-signals = "5.0.0"
xattr = "1.6.1"
serde_json = "1.0.145"
ssh2 = "0.9"
extism = "1.0"

[dev-dependencies]
assert_fs = "1.1.3"
assert_cmd = "2.0.17"
predicates = "3.1.3"

# Binary removed - this is a library package

[lib]
name = "cylo"
path = "src/lib.rs"

# Linux-specific dependencies
[target.'cfg(target_os = "linux")'.dependencies]
landlock = { version = "0.4.3", optional = true }

[features]
default = ["landlock"]
landlock = ["dep:landlock"]
