[package]
name = "rio-ext-test"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[lib]
name = "sixel_renderer"
path = "src/renderer/mod.rs"

[dependencies]
anyhow = "1.0.98"
chromiumoxide = { version = "0.7.0", features = ["tokio-runtime"] }
chromiumoxide_cdp = "0.7.0"
futures = "0.3.31"
serde_json = "1.0.140"
tempfile = "3.20.0"
tokio = { version = "1.45", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["fmt"] }

# Build automation dependencies
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
toml_edit = "0.23.6"
hex = "0.4"
sha2 = "0.10"
ring = "0.17"
semver = { version = "1.0", features = ["serde"] }
heapless = { version = "0.8", features = ["serde"] }

# Core dependencies for sixel renderer
image = "0.25.6"

# Optional test harness dependencies
image-compare = { version = "0.4.1", optional = true }
sixel-tokenizer = { version = "0.1.0", optional = true }
pollster = { version = "0.4", optional = true }

# Rio integration - optional test harness only
rio_window = { package = "rio-window", git = "https://github.com/raphamorim/rio", tag = "v0.2.31", default-features = false, optional = true }
rio_backend = { package = "rio-backend", git = "https://github.com/raphamorim/rio", tag = "v0.2.31", optional = true }
sugarloaf = { package = "sugarloaf", git = "https://github.com/raphamorim/rio", tag = "v0.2.31", optional = true }
teletypewriter = { package = "teletypewriter", git = "https://github.com/raphamorim/rio", tag = "v0.2.31", optional = true }
raw-window-handle = { version = "0.6.2", optional = true }
base64 = { version = "0.22.1", optional = true }
percent-encoding = { version = "2.3.1", optional = true }
thiserror = { version = "2.0.12", optional = true }
wgpu = { version = "25.0.0", optional = true }

# Platform-specific signing dependencies
[target.'cfg(target_os = "macos")'.dependencies]
tauri-macos-sign = "2.1.0"
security-framework = "2.11"
core-foundation = "0.10"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3", features = ["wincrypt", "winreg", "processthreadsapi"] }
windows = { version = "0.61", features = [
  "Win32_Foundation",
  "Win32_Security_Cryptography",
  "Win32_System_Registry",
  "Win32_System_Threading"
] }

[target.'cfg(target_os = "linux")'.dependencies]
gpgme = "0.11"
deb = "0.5"

[features]
default = []
rio-test-harness = [
    "image-compare",
    "sixel-tokenizer",
    "pollster",
    "rio_window",
    "rio_backend",
    "sugarloaf",
    "teletypewriter",
    "raw-window-handle",
    "base64",
    "percent-encoding",
    "thiserror",
    "wgpu",
]

[[bin]]
name = "rio-ext-test"
path = "src/main.rs"
required-features = ["rio-test-harness"]

[[bin]]
name = "build-installers"
path = "build-installers.rs"
