[package]
name = "sixel6vt"
version = "0.1.0"
edition = "2024"

[lib]
name = "sixel_renderer"
path = "src/renderer/mod.rs"

[dependencies]
anyhow = "1.0.98"
chromiumoxide = { version = "0.7.0", features = ["tokio-runtime"] }
chromiumoxide_cdp = "0.7.0"
futures = "0.3.31"
serde_json = "1.0.140"
tempfile = "3.20.0"
tokio = { version = "1.45", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["fmt"] }

# Core dependencies for sixel renderer
image = "0.25.6"

# Rio terminal integration
rio_window = { package = "rio-window", git = "https://github.com/raphamorim/rio", tag = "v0.2.31", default-features = false }
rio_backend = { package = "rio-backend", git = "https://github.com/raphamorim/rio", tag = "v0.2.31" }
sugarloaf = { package = "sugarloaf", git = "https://github.com/raphamorim/rio", tag = "v0.2.31" }
teletypewriter = { package = "teletypewriter", git = "https://github.com/raphamorim/rio", tag = "v0.2.31" }
raw-window-handle = "0.6.2"
base64 = "0.22.1"
percent-encoding = "2.3.1"
thiserror = "2.0.12"
wgpu = "25.0.0"

[[bin]]
name = "sixel6vt"
path = "src/main.rs"
