[package]
name = "sweetmcp-stdio-client"
version = "0.1.0"
edition = "2024"
description = "STDIO-based client for SweetMCP protocol communication"
license = "MIT OR Apache-2.0"
repository = "https://github.com/cyrusnimda/cyrup"
readme = "README.md"
keywords = ["mcp", "stdio", "client", "protocol", "ipc"]
categories = ["api-bindings", "network-programming"]

[dependencies]
serde_json = "1.0"
tokio = { version = "1.47", features = ["full"] }
log = { workspace = true }
thiserror = "2.0"
sweet_mcp_type = { path = "../sweet-mcp-type", package = "sweet_mcp_type" }
mcp-client-traits = { path = "../mcp-client-traits" }
uuid = { version = "1.18", features = ["v4"] }
simd-json = { version = "0.16.0", default-features = false, features = ["known-key", "runtime-detection", "swar-number-parsing", "value-no-dup-keys"] }
