[package]
name = "sweetmcp-graphql-client"
version = "0.1.0"
edition = "2024"
authors = ["CYRUP AI"]
description = "GraphQL client for SweetMCP protocol using async-graphql schema generation"
license = "MIT OR Apache-2.0"
repository = "https://github.com/cyrusnimda/paraphym"
readme = "README.md"
keywords = ["mcp", "graphql", "client", "protocol", "async"]
categories = ["api-bindings", "network-programming"]

[dependencies]
# Core MCP types and high-performance JSON processing
sweet_mcp_type = { path = "../sweet-mcp-type" }
mcp-client-traits = { path = "../mcp-client-traits" }

# GraphQL support
async-graphql = { version = "7.0.17", features = ["chrono", "url", "uuid"] }

# Async runtime
tokio = { version = "1.47.1", features = ["full"] }

# HTTP client  
reqwest = { version = "0.12.23", features = ["json"] }

# Error handling
thiserror = "2.0.17"
anyhow = "1.0.100"

# UUID generation for request IDs
uuid = { version = "1.18.1", features = ["v4"] }

# Logging and tracing
tracing = "0.1.41"
tracing-subscriber = "0.3.20"

# High-performance JSON (matching sweet-mcp-type)
simd-json = { version = "0.16.0", default-features = false, features = ["known-key", "runtime-detection", "swar-number-parsing", "value-no-dup-keys"] }

# JSON value trait for object access
value-trait = "0.11.0"

# Time handling for GraphQL schema
chrono = { version = "0.4.42", features = ["serde"] }

# JSON serialization for GraphQL responses
serde_json = "1.0.145"

[dev-dependencies]
# Testing utilities
tokio-test = "0.4.4"
pretty_assertions = "1.4.1"
