[package]
name = "sweetmcp-pingora"
version = "0.3.1"
edition = "2024"
description = "SweetMCP Server • Sugora gateway (Pingora 0.5, OTEL, Unix-socket CLI)"
authors = ["SweetMCP Team"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/sweetmcp/server"
readme = "README.md"
keywords = ["mcp", "gateway", "proxy", "pingora", "opentelemetry"]
categories = ["network-programming", "web-programming", "api-bindings"]

[dependencies]
# Core Pingora dependencies - using local fork with mTLS support
pingora = { path = "../../../../forks/pingora/pingora", features = ["proxy", "lb", "rustls"] }
pingora-proxy = { path = "../../../../forks/pingora/pingora-proxy" }
pingora-load-balancing = { path = "../../../../forks/pingora/pingora-load-balancing" }
pingora-rustls = { path = "../../../../forks/pingora/pingora-rustls" }

# CLI argument parsing
clap = { version = "4.5", features = ["derive"] }

# Async runtime
tokio = { version = "1.47", features = ["macros", "rt-multi-thread", "sync", "fs", "net", "time", "signal"] }

# MCP SDK - removed, using sweetmcp-axum instead
sweetmcp-axum = { path = "../axum" }

# Protocol parsing
async-graphql = { version = "7", features = ["tracing"] }
async-graphql-value = "7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
capnp = "0.21"

# Authentication & Security
jsonwebtoken = "10.0"
ring = "0.17"
uuid = { version = "1.18", features = ["v4", "serde"] }
hex = "0.4"

# Observability
opentelemetry = { version = "0.31", features = ["trace", "metrics"] }
opentelemetry_sdk = { version = "0.31", features = ["trace", "metrics"] }
opentelemetry-prometheus = "0.29"
opentelemetry-jaeger = "0.22"
prometheus = { version = "0.14", features = ["process"] }

# System monitoring
sysinfo = { version = "0.37.2", features = ["multithread"] }

# Configuration & Environment
env_logger = "0.11"
log = "0.4"
termcolor = { workspace = true }
dotenvy = "0.15"
config = { version = "0.15", features = ["yaml", "toml"] }

# Error handling
anyhow = "1.0"
thiserror = "2.0"

# Utilities
once_cell = "1.21"
dirs = "6.0"
seahash = "4.1"
bytes = "1.10"
base64-url = "3.0"
base64 = "0.22"
prometheus-parser = "0.4"

# Lock-free performance optimizations
arc-swap = "1.7"                # Lock-free atomic operations on Arc
atomic-counter = "1.0"          # Atomic counters for statistics
dashmap = "6.1"                 # Concurrent HashMap for rate limiting

# HTTP client for peer communication
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "json", "stream"] }

# DNS resolver for service discovery
hickory-resolver = { version = "0.25", features = ["tokio"] }

# Rate limiting
governor = "0.10"
nonzero_ext = "0.3"

# Additional security
time = { version = "0.3", features = ["serde", "macros", "formatting"] }
rand = "0.9"
url = "2.5"
rustls = { version = "0.23", features = ["std"] }
rustls-pemfile = "2.2"
rcgen = { version = "0.14", features = ["pem"] }
hostname = "0.4"
sodiumoxide = "0.2"
x509-parser = { version = "0.18", features = ["verify"] }
zeroize = { version = "1.8.2", features = ["derive"] }
age = { version = "0.11.1", features = ["armor"] }
webpki = { version = "0.22.4", features = ["std"] }
webpki-roots = "1.0.2"
rustls-native-certs = "0.8"
keyring = "3"
pem = "3.0"
der = { version = "0.7", features = ["derive", "oid", "std"] }
x509-cert = { version = "0.2", features = ["builder"] }
x509-ocsp = { version = "0.2", default-features = false }

# Feature-gated dependencies
futures = "0.3"
pin-project = "1.1"

# Additional TLS dependencies from quyc
http = "1"
hyper = { version = "1.7", features = ["http1", "client"] }
hyper-util = { version = "0.1", features = ["http1", "http2", "client", "client-legacy"] }
http-body-util = "0.1"
hyper-rustls = "0.27"
tokio-rustls = "0.26"
const-oid = { version = "0.10", features = ["db"] }
hmac = "0.12"
sha2 = "0.10"

[dev-dependencies]
# Testing framework
tokio-test = "0.4"
proptest = "1.8"
criterion = { version = "0.7", features = ["html_reports"] }
tempfile = "3.23"
wiremock = "0.6"

# Load testing
hyper = { version = "1.7", features = ["full"] }
tower = "0.5"

[features]
default = ["production"]
production = []
development = []
testing = []

# Benchmarks will be added later
# [[bench]]
# name = "protocol_parsing"
# harness = false

# [[bench]]
# name = "load_balancing"
# harness = false

[lib]
name = "sweetmcp"
path = "src/lib.rs"

[[bin]]
name = "sweetmcp_server"
path = "src/main.rs"
