[package]
name = "sweetmcp-capnp-client"
version = "0.1.0"
edition = "2024"
description = "Cap'n Proto client for SweetMCP protocol extension demonstration"

[dependencies]
capnp = "0.21.5"
serde_json = "1.0.145"
tokio = { version = "1.47.1", features = ["full"] }
reqwest = { version = "0.12.23", features = ["json"] }
anyhow = "1.0.100"
uuid = { version = "1.18.1", features = ["v4"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.20"

[build-dependencies]
capnpc = "0.21.4"
