[package]
name = "paraphym_candle"
version = "0.1.0"
edition = "2024"
description = "High-performance AI framework with fluent API for building agents using Candle ML"
license = "MIT"
repository = "https://github.com/cyrusnimda/paraphym"
readme = "README.md"
keywords = ["ai", "ml", "agents", "candle", "inference"]
categories = ["science", "mathematics", "algorithms", "api-bindings"]


[dependencies]
bitflags = { version = "2.9.4", features = ["serde"] }
paraphym_simd = { path = "../simd" }
cylo = { path = "../cylo" }
ctrlc = { version = "3.4", features = ["termination"] }

# SweetMCP dependencies for proper MCP implementation
sweetmcp-json-client = { path = "../sweetmcp/packages/json-client" }
sweetmcp-stdio-client = { path = "../sweetmcp/packages/stdio-client" }
mcp-client-traits = { path = "../sweetmcp/packages/mcp-client-traits" }
sweet_mcp_type = { path = "../sweetmcp/packages/sweet-mcp-type" }
simd-json = { version = "0.16.0", default-features = false, features = ["known-key", "runtime-detection", "swar-number-parsing", "value-no-dup-keys"] }
value-trait = "0.11.0"
shell-words = "1.1"
quyc = { git = "https://github.com/cyrup-ai/quyc", branch = "main", package = "quyc" }  
cyrup_sugars = { git = "https://github.com/cyrup-ai/cyrup-sugars", branch = "main", package = "cyrup_sugars", features = ["all"] }
ystream = { git = "https://github.com/cyrup-ai/ystream", branch = "main", package = "ystream" }
progresshub = { git = "https://github.com/cyrup-ai/progresshub", branch = "main", package = "progresshub", optional = true }

# Add hf-hub as optional dependency
hf-hub = { version = "0.3", optional = true, default-features = false, features = ["online", "tokio"] }

# For finding home directory
dirs = "5.0"

# Extension integration dependencies (STUBFIX_25)
quick-xml = { version = "0.36", features = ["serialize"] }
plist = "1.8"

# SurrealDB and its features
surrealdb = { path = "../../forks/surrealdb/crates/sdk", features = ["http", "protocol-http", "kv-surrealkv"] }

# Async runtime (from memory package)
futures = { version = "0.3.31" }
async-channel = { version = "2.5.0" }

# Error handling (from memory package)
anyhow = { version = "1.0.100" }

# File watching for realtime context updates
notify = "8.2"

# Memory utilities (from memory package)
memchr = { version = "2.7.6" }

# MIME type detection
mime_guess = "2.0"

# Cognitive system dependencies (from memory package)
ndarray = { version = "0.16.1" }
nalgebra = { version = "0.34", features = ["serde-serialize"] }
petgraph = { version = "0.8.3" }
ordered-float = { version = "5.1.0" }

# Crypto/hashing (from memory package)
sha2 = { version = "0.11.0-rc.2" }

# File system (from memory package)
walkdir = { version = "2.5.0" }

# Git operations
git2 = { version = "0.20", default-features = false, features = ["https", "ssh"] }

# Complex numbers (from memory package)
num-complex = { version = "0.4.6" }

# Vector store implementations (from memory package)
faiss = { version = "0.12.1", optional = true }
hnsw = { version = "0.11.0", optional = true }
instant-distance = { version = "0.6.1" }

# HTTP API (from memory package)
axum = { version = "0.8.6", optional = true }
tower = { version = "0.5.2", optional = true }
tower-http = { version = "0.6.6", features = ["cors", "trace"], optional = true }

# Additional utilities (from memory package)
atomic = "0.6.1"
jsonwebtoken = "10.0.0"
csv = "1.3.1"
prometheus = { version = "0.14.0" }


# — DSP / NN (base dependencies - no acceleration features) —
candle-core = { git = "https://github.com/huggingface/candle", branch = "main", default-features = false }
candle-nn = { git = "https://github.com/huggingface/candle", branch = "main", default-features = false }
candle-transformers = { git = "https://github.com/huggingface/candle", branch = "main", default-features = false }
tokenizers = "0.22.1"

# — Optional acceleration dependencies —
half = { version = "2.6.0", optional = true }
metal = { version = "0.32.0", optional = true }
candle-metal-kernels = { git = "https://github.com/huggingface/candle", branch = "main", optional = true }
cudarc = { version = "0.17.3", optional = true, default-features = false, features = [
    "cublas",
    "cublaslt", 
    "cudnn",
    "curand",
    "dynamic-linking",
    "f16",
    "std",
] }
bindgen_cuda = { version = "0.1.5", optional = true }
candle-kernels = { git = "https://github.com/huggingface/candle", branch = "main", optional = true }

# — audio / resampling —
hound = "3.5.1"
symphonia = { version = "0.5.4", features = ["all"], optional = true }

# Core dependencies
serde = { version = "1.0.228", features = ["derive"] }
schemars = { version = "1.0", features = ["derive"] }
jsonschema = "0.33"
thiserror = "2.0.17"
uuid = { version = "1.18.1", features = ["v4", "serde"] }
serde_json = "1.0.145"
log = { workspace = true }
env_logger = { workspace = true }
termcolor = { workspace = true }
hashbrown = { version = "0.16.0", features = ["serde"] }
glob = "0.3.3"
base64 = "0.22.1"
image = { version = "0.25.8", default-features = false, features = ["png", "jpeg"] }

# CLI dependencies for interactive prompts
inquire = { version = "0.7", features = ["fuzzy"] }
fuzzy-matcher = "0.3"

# Content sanitization dependencies (TASK404)
unicode-normalization = "0.1.24"  # Unicode NFC normalization for security
html-escape = "0.2"               # HTML entity escaping for XSS prevention

# Content formatting (STUB_1)
pulldown-cmark = "0.11"
syntect = "5.3"

# --- Web dependencies ---
wasm-bindgen = { version = "0.2.104", optional = true }
js-sys = { version = "0.3.81", optional = true }
web-sys = { version = "0.3.81", optional = true }
console_error_panic_hook = { version = "0.1.7", optional = true }
jwalk = "0.8.1"
flume = "0.11.1"
rayon = { version = "1.11.0", optional = true }
gix = "0.73.0"
yyaml = { git = "https://github.com/cyrup-ai/yyaml", branch = "main"}
memmap2 = "0.9.8"
ignore = "0.4.23"
ahash = "0.8.12"
chrono = { version = "0.4.42", features = ["serde"] }

# Ultra-high-performance dependencies for zero-allocation operations
arrayvec = { version = "0.7.6", features = ["serde"] }
smallvec = { version = "2.0.0-alpha.11", features = ["serde"] }

# System information for memory queries
sysinfo = "0.30"
crossbeam-deque = "0.8.6"
crossbeam-skiplist = "0.1.3"
crossbeam-utils = "0.8.21"
crossbeam-queue = "0.3.12"
crossbeam-channel = "0.5.15"
crossbeam = "0.8.4"
cache-padded = "1.3.0"

wide = "0.7.33"
futures-util = { version = "0.3.31", default-features = false, features = ["std"] }
lazy_static = "1.5.0"
ropey = "2.0.0-beta.1"
atomic-counter = "1.0.1"
arc-swap = "1.7.1"
once_cell = "1.21.3"
regex = "1.11.3"
minijinja = "2.12"
parking_lot = "0.12.5"
dashmap = "6.1.0"
strsim = "0.11.1"
lz4 = "1.28.1"

# LRU cache for operation history tracking
moka = { version = "0.12", features = ["sync"] }

# Additional dependencies for memory migration
fastrand = "2.3.0"
rand = "0.9.2"
rand_pcg = "0.9.0"
num_cpus = "1.17.0"
bytes = "1.10.1"
toml = "0.9.7"
rkyv = { version = "0.8.12", optional = true }
bincode = { version = "2.0.1" }

# Note: SurrealDB already defined above, removing duplicate
serde_cbor = "0.11.2"

md5 = "0.8.0"
tokio = { version = "1.47.1", features = ["full"] }
tokio-stream = "0.1.17"
rustls = { version = "0.23", features = ["aws-lc-rs"], default-features = false }
async-stream = "0.3.6"
clap = { version = "4.5.48", features = ["derive"] }

# HuggingFace Hub download dependencies
reqwest = { version = "0.12", features = ["json", "rustls-tls"], optional = true, default-features = false }
globset = { version = "0.4", optional = true }

[dev-dependencies]
# Testing (from memory package)
mockall = { version = "0.13.1" }
mockito = { version = "1.7.0" }
assert_approx_eq = { version = "1.1.0" }
criterion = { version = "0.7.0" }
tempfile = { version = "3.23.0" }
env_logger = { workspace = true }
jemalloc-sys = "0.5.4"
quanta = "0.12.6"
weak-table = "0.3.2"
fnv = "1.0.7"
hdrhistogram = "7.5.4"


[[bin]]
name = "paraphym"
path = "src/main.rs"

[lib]
name = "paraphym_candle"
path = "src/lib.rs"


[features]
# NOTE: Providers currently only implement ProgressHub backend. HF-Hub implementations needed.
default = ["metal", "reqwest_unstable", "cognitive", "api", "download-hf-hub"]

# --- Core build flavours ---
desktop = ["dep:rayon"]
web = ["dep:wasm-bindgen", "dep:js-sys", "web-sys/Window", "dep:console_error_panic_hook"]

# --- Developer conveniences ---
dev = ["debug", "desktop"]
debug = []

# --- SIMD features ---
portable_simd = []
reqwest_unstable = []

# --- Memory package features (migrated) ---
api = ["dep:axum", "dep:tower", "dep:tower-http"]
faiss-vector = ["dep:faiss"]
hnsw-vector = ["dep:hnsw"]
surreal-vector = []
custom-embeddings = []
cognitive = []
quantum-routing = ["cognitive"]
evolution = ["cognitive"]
full-cognitive = ["cognitive", "quantum-routing", "evolution"]

# --- Download backend features (can be used together, hf-hub is default) ---
download-hf-hub = ["dep:hf-hub", "dep:reqwest", "dep:globset"]
download-progresshub = ["dep:progresshub"]

# --- Candle backend features ---
cuda = [
    "dep:cudarc",
    "dep:bindgen_cuda", 
    "dep:candle-kernels",
    "candle-core/cuda",
    "candle-nn/cuda",
    "candle-transformers/cuda",
]
cudnn = ["cuda", "cudarc/cudnn"]
metal = [
    "dep:metal",
    "dep:candle-metal-kernels",
    "candle-core/metal",
    "candle-nn/metal", 
    "candle-transformers/metal",
]
accelerate = [
    "dep:accelerate-src",
    "candle-core/accelerate",
    "candle-nn/accelerate",
    "candle-transformers/accelerate",
]
mkl = [
    "dep:intel-mkl-src",
    "candle-core/mkl",
    "candle-nn/mkl",
    "candle-transformers/mkl",
]

# OS-specific acceleration dependencies
[target.'cfg(all(target_os = "linux", target_arch = "x86_64"))'.dependencies]
intel-mkl-src = { version = "0.8.1", optional = true }

[target.'cfg(all(target_os = "windows", target_arch = "x86_64"))'.dependencies]
intel-mkl-src = { version = "0.8.1", optional = true }

[target.'cfg(target_os = "macos")'.dependencies]
accelerate-src = { version = "0.3.2", optional = true }
